### ISSUE TITLE
Support configuring msg deduplication strategy

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/jetstream#275]
From https://github.com/nats-io/jetstream/blob/master/README.md#message-deduplication , it seems to me that jetstream currently uses first_arrived_wins strategy for deduplication. I would like to request an option to configure that:

- last_arrived_wins
- Msg-Version: Int64 where user can pass an integer that represents version number and the higher version wins.

My use-case is that I am routing Kubernetes resource updates via jetstream and in my case I only need to process the latest version of an object (msg-id).

**Comment by ripienaar** [comment]
Personally with a stream I dont think last wins is a good option to have, you have a few options:

 * Make it a work queue and acknowledged messages will be removed, so you'd only be processing the last
 * Use a CQRS like model to apply changes to your representations

wdyt @derekcollison

**Comment by tamalsaha** [comment]
`Msg-Version` will be helpful since k8s objects have generation field.

**Comment by derekcollison** [comment]
If the message is the same and susceptible to deduplication why does it matter, both should be the same no?

**Comment by tamalsaha** [comment]
In my case, the messages are Kubernetes update events. The message body is about the same object (say, pod or service) but the actual body is the updated version (not same). In Kubernetes world, we only need to reconcile the updated version only.

**Comment by derekcollison** [comment]
For them would we just have a jetstream stream of limit of messages of 1, meaning last one in is always the one available?

**Comment by tamalsaha** [comment]
I am thinking more like a subject k8s.c1.pods where all update events related to pods from a single k8s cluster will be sent to a jetstream . So, I don't think message limit 1 will work.

**Comment by derekcollison** [comment]
Depending on how many distinct events you could use a template and have each one be its own stream?

**Comment by tamalsaha** [comment]
In theory yes. But this feels a bit extreme :) . How many streams can be 2 CPU 4-8GB ram jetstream deployment handle?

**Comment by derekcollison** [comment]
Streams should be considered as fairly light weight from a construct point of view. I would not hesitate to have a template create hundreds or thousands of streams.

Easy to test out and play with..

**Comment by izwerg** [comment]
"last arrived wins" makes sense. For example, you have an entity, e.g. order. Instead of emitting an event with order delta, you emit an event with full order snapshot on any change in that order. Thus, you have a stream of order snapshots. If a stream has multiple snapshot events for a certain order, only the last snapshot for that order makes sense.

To get advantage of deduplication with "last arrived wins", you should assign order ID (primary key) to Nats-Msg-Id. Thus, you cover all these requirements for cross-service data synchronization:
**1. No data loss on service-consumer downtime.** - this is clear - durable consumer
**2. Feeding new services with fresh data.** - a new empty service only needs the latest snapshot event for each order.
**3. Limited stream size due to deduplication instead of retention.** - if you enable retention in case of event sourcing, a new empty service can't restore full state due to events loss. If you disable retention - you have eternal event stream and a new empty service has to waste time on replaying old snapshots. "last arrived wins" strategy allows having predictable size of event stream due to deduplication and having durable and optimized data synchronization between services. This is some kind of "hybrid event sourcing" when you emit snapshots instead of deltas.

By the way, Liftbridge implements "last arrived wins" strategy, they call it "log compaction":
> Additionally, Liftbridge supports log compaction. Publishers can, optionally, set a key on a message envelope. A stream can be configured to compact by key. In this case, it retains only the last message for each unique key. Messages that do not have a key are always retained.
[https://liftbridge.io/docs/concepts.html#stream-retention-and-compaction](https://liftbridge.io/docs/concepts.html#stream-retention-and-compaction)

**Comment by ripienaar** [comment]
I previously wrote up a internal feature request, currently not being implemented though:

```
**Message Rollups**

It would be great to support rollups of messages, meaning if 100 previous messages is combined 
into the last 1 message then the previous 100 can be deleted.

One possible way to do this is using headers, if messages are published to subject `in.x` when a 
message with header `JS-Rollup: in.x` is received on subject `in.x` then all previous messages 
received on that subject can be removed.  No doubt other ways but this is one possibility

This could be done with templates if you could purge up to a specific message ID but today purge 
is all messages.  Also templates mght not scale to a large case for this feature
via discussion with Igor Anic on slack
```

**Comment by derekcollison** [comment]
I vacillate back and forth between making some of these small changes and swinging back to this should be a different stream.

That being said, we have conditional publish now with headers to match last msgId or seq, we could add one that says "iff" you accept this message purge til this point. Not sure that gets us everything we need, but I do support a single stream that can be rolled up and snapshotted effectively.

**Comment by ripienaar** [comment]
rollups into a seperate stream would be very hard to use, ideally rolling up would not affect any of the current consumers - they'd just get the latest rollup data.  Would need to support wildcards, and will finally get me my requested purge up to seq feature.

Agree though, we should do this after GA after a period of focussing on higher order use cases which is why I never really passed on this feature request properly

**Comment by derekcollison** [comment]
I have done these types of systems in the past, they are useful but also tricky to get really right. We need to think more about consumers who are behind the stream itself and what happens to them when you rollup and purge.

**Comment by ripienaar** [comment]
We have dedup now, I still want rollups. But lets close this one for the moment.
