### ISSUE TITLE
Block Storage Support

### ISSUE THREAD

**Issue by Ryner51** [nats-io/jetstream#331]
For users that are running in K8S, we would like access to a Block Storage device for faster performance rather than using the Cloud Native abstraction layer to the Data Storage. With Block Storage, we can mount the storage to the Pod as a shared file system across numerous pods.

**Comment by ripienaar** [comment]
Just to clarify: do you mean you would like to mount this same block device on multiple machines at the same time and have us write data to it from all active servers?  This is model you might see in MS SQL Servers sharing a platter of Fibre Channel disks and with a small 2nd partition that's used to manage the quorum, but on the main storage platters isnt a POSIX like filesystem its a file layout unique to MS SQL.  Is that what you had in mind?

Our current planned JS model is that each machine would have an independent storage and would contribute that resources to a pool of available resources. Rather than any form of shared file system requirement at all, in fact I don't think we will support something like the same NFS mount on all machines - no form of sharing the same storage between 2 JS nodes. 

I also don't think we'll be writing to a raw block device - we'd require a POSIXish filesystem for the near storage.

We might support archival quality storage to say S3, but not as a primar store.

**Comment by ripienaar** [comment]
Closing this, not sure what the desire is here but feel free to reopen with more information
