### ISSUE TITLE
Jetstream Operator or NATS Operator support?

### ISSUE THREAD

**Issue by nfrush** [nats-io/jetstream#439]
I know, I'm asking things that are definitely "on the backburner" in terms of roadmap objectives. I'm just wondering whether we'll see support in the NATS Operator eventually or it'll go the way of the NATS Streaming Operator (i.e. a separate operator).

**Comment by wallyqs** [comment]
NATS Operator would not have JetStream support since have to change from controlling Pods to StatefulSets which will break many things, so it would be a different controller part of this repo: https://github.com/nats-io/nack
That repo already includes some CRDs for streams/consumers, though to create the cluster itself the helm charts would be recommended: https://github.com/nats-io/k8s/tree/master/helm/charts/nats#jetstream

**Comment by nfrush** [comment]
@wallyqs Didn't even known these existed. Thank you so much for pointing them out :)
